type Mutation {

	# Login__________________________________________________

	"Login"
	login(
		account:String!,
		password:String!,
	): UserLoginData!

	# User__________________________________________________

	"Create a new user."
  userCreate(
    input: InputUserCreate!,
  ): User!

  "Update an exist user."
  userUpdate(
		"User Id"
		id: ScalarUUID!,
    input: InputUserUpdate!,
  ): User!

  "Delete an exist user, return deleted user id."
  userDelete(
    "User ID."
    id: ScalarUUID!,
  ): String!

}