type Query {
	"""return "world"."""
	hello: String
	hello2: String
	hello3(
		"return name"
		name: String
	): String

	"Get service info."
  service: ServiceInfo!

	"Get current user informations, and permissions."
	me: Me

	"Get all users"
	users: [User]!
}